<?xml version="1.0" encoding="utf-8"?>
	<annotation>
		<folder>driving_annotation_dataset</folder>
		<filename>shoot325_5.jpg</filename>
		<size>
			<width>608</width>
			<height>608</height>
			<depth>3</depth>
		</size>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>377</xmin>
				<ymin>258</ymin>
				<xmax>498</xmax>
				<ymax>414</ymax>
			</bndbox>
		</object>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>472</xmin>
				<ymin>234</ymin>
				<xmax>553</xmax>
				<ymax>386</ymax>
			</bndbox>
		</object>
	</annotation>
