<?xml version="1.0" encoding="utf-8"?>
	<annotation>
		<folder>driving_annotation_dataset</folder>
		<filename>shoot212_2.jpg</filename>
		<size>
			<width>608</width>
			<height>608</height>
			<depth>3</depth>
		</size>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>91</xmin>
				<ymin>492</ymin>
				<xmax>209</xmax>
				<ymax>609</ymax>
			</bndbox>
		</object>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>388</xmin>
				<ymin>422</ymin>
				<xmax>511</xmax>
				<ymax>609</ymax>
			</bndbox>
		</object>
	</annotation>
