<?xml version="1.0" encoding="utf-8"?>
	<annotation>
		<folder>driving_annotation_dataset</folder>
		<filename>shoot600_5.jpg</filename>
		<size>
			<width>608</width>
			<height>608</height>
			<depth>3</depth>
		</size>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>302</xmin>
				<ymin>321</ymin>
				<xmax>382</xmax>
				<ymax>460</ymax>
			</bndbox>
		</object>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>348</xmin>
				<ymin>374</ymin>
				<xmax>430</xmax>
				<ymax>467</ymax>
			</bndbox>
		</object>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>263</xmin>
				<ymin>339</ymin>
				<xmax>316</xmax>
				<ymax>461</ymax>
			</bndbox>
		</object>
	</annotation>
