<annotation>
	<folder>image2</folder>
	<filename>shoot664_5.jpg</filename>
	<path>D:\柑橘花\image2\shoot664_5.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>608</width>
		<height>608</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>104</xmin>
			<ymin>307</ymin>
			<xmax>181</xmax>
			<ymax>442</ymax>
		</bndbox>
	</object>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>94</xmin>
			<ymin>443</ymin>
			<xmax>152</xmax>
			<ymax>505</ymax>
		</bndbox>
	</object>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>181</xmin>
			<ymin>377</ymin>
			<xmax>224</xmax>
			<ymax>451</ymax>
		</bndbox>
	</object>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>217</xmin>
			<ymin>253</ymin>
			<xmax>282</xmax>
			<ymax>381</ymax>
		</bndbox>
	</object>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>523</xmin>
			<ymin>244</ymin>
			<xmax>593</xmax>
			<ymax>310</ymax>
		</bndbox>
	</object>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>482</xmin>
			<ymin>197</ymin>
			<xmax>532</xmax>
			<ymax>263</ymax>
		</bndbox>
	</object>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>456</xmin>
			<ymin>225</ymin>
			<xmax>494</xmax>
			<ymax>264</ymax>
		</bndbox>
	</object>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>530</xmin>
			<ymin>456</ymin>
			<xmax>567</xmax>
			<ymax>509</ymax>
		</bndbox>
	</object>
</annotation>
