<annotation>
	<folder>image2</folder>
	<filename>shoot639_5.jpg</filename>
	<path>D:\柑橘花\image2\shoot639_5.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>608</width>
		<height>608</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>71</xmin>
			<ymin>8</ymin>
			<xmax>176</xmax>
			<ymax>144</ymax>
		</bndbox>
	</object>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>352</xmin>
			<ymin>318</ymin>
			<xmax>439</xmax>
			<ymax>466</ymax>
		</bndbox>
	</object>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>443</xmin>
			<ymin>351</ymin>
			<xmax>562</xmax>
			<ymax>498</ymax>
		</bndbox>
	</object>
	<object>
		<name>shoot</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>166</xmin>
			<ymin>374</ymin>
			<xmax>276</xmax>
			<ymax>453</ymax>
		</bndbox>
	</object>
</annotation>
