<?xml version="1.0" encoding="utf-8"?>
	<annotation>
		<folder>driving_annotation_dataset</folder>
		<filename>shoot350_5.jpg</filename>
		<size>
			<width>608</width>
			<height>608</height>
			<depth>3</depth>
		</size>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>83</xmin>
				<ymin>174</ymin>
				<xmax>162</xmax>
				<ymax>333</ymax>
			</bndbox>
		</object>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>264</xmin>
				<ymin>118</ymin>
				<xmax>348</xmax>
				<ymax>269</ymax>
			</bndbox>
		</object>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>124</xmin>
				<ymin>482</ymin>
				<xmax>272</xmax>
				<ymax>606</ymax>
			</bndbox>
		</object>
	</annotation>
