<?xml version="1.0" encoding="utf-8"?>
	<annotation>
		<folder>driving_annotation_dataset</folder>
		<filename>shoot575_5.jpg</filename>
		<size>
			<width>608</width>
			<height>608</height>
			<depth>3</depth>
		</size>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>17</xmin>
				<ymin>117</ymin>
				<xmax>153</xmax>
				<ymax>228</ymax>
			</bndbox>
		</object>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>181</xmin>
				<ymin>281</ymin>
				<xmax>303</xmax>
				<ymax>447</ymax>
			</bndbox>
		</object>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>189</xmin>
				<ymin>434</ymin>
				<xmax>328</xmax>
				<ymax>552</ymax>
			</bndbox>
		</object>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>248</xmin>
				<ymin>247</ymin>
				<xmax>383</xmax>
				<ymax>411</ymax>
			</bndbox>
		</object>
		<object>
			<name>shoot</name>
			<pose>Unspecified</pose>
			<truncated>0</truncated>
			<difficult>0</difficult>
			<bndbox>
				<xmin>428</xmin>
				<ymin>325</ymin>
				<xmax>560</xmax>
				<ymax>474</ymax>
			</bndbox>
		</object>
	</annotation>
